version: "3.2"
services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - db_store
    environment:
      - "AWS_ACCESS_KEY=test"
      - "AWS_SECRET_KEY=test"
      - "DYNAMO_DATABASE_HOST=localhost"
      - "DYNAMO_DATABASE_PORT=8000"
    network_mode: "host"
  db_store:
    image: "amazon/dynamodb-local:latest"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data
    network_mode: "host"