version: "3.2"
services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    tty: true
    depends_on:
      - db_store
    environment:
      - "AWS_ACCESS_KEY=test"
      - "AWS_SECRET_KEY=test"
      - "DYNAMO_DATABASE_HOST=localhost"
      - "DYNAMO_DATABASE_PORT=8000"
    network_mode: "host"
  db_store:
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000" 
    network_mode: "host"